<?php

namespace AppBundle\Repository;

/**
 * VoyagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyagesRepository extends \Doctrine\ORM\EntityRepository
{
}
